"""JAX-backed spectral analysis tools for ``powerbox`` fields."""

from __future__ import annotations

import warnings
from collections.abc import Callable, Sequence
from dataclasses import dataclass

import jax
import jax.numpy as jnp
import numpy as np
from scipy.special import gamma

from . import dft


def _is_scalar(value: object) -> bool:
    """Return whether *value* behaves like a scalar."""
    return np.isscalar(value) or getattr(value, "ndim", None) == 0


@dataclass
class PowerSpectrum:
    """The result of :func:`get_power` for JAX-backed arrays.

    Parameters
    ----------
    power : jax.Array
        The angularly averaged power spectrum.
    bin_edges : jax.Array
        The edges of the radial bins.
    bin_centres : jax.Array
        The centres of the radial bins.
    bin_avg : jax.Array, optional
        The weighted average k-mode in each radial bin.
    nsamples : jax.Array, optional
        The effective number of samples in each radial bin.
    variance : jax.Array, optional
        The estimated variance of the power spectrum in each radial bin.
    k_unbinned : tuple of jax.Array, optional
        The k-axis arrays for dimensions that were not angularly averaged.
    """

    power: jax.Array
    bin_edges: jax.Array
    bin_centres: jax.Array
    bin_avg: jax.Array | None = None
    nsamples: jax.Array | None = None
    variance: jax.Array | None = None
    k_unbinned: tuple[jax.Array, ...] | None = None

    def __post_init__(self) -> None:
        """Validate and normalize array-valued fields."""
        self.power = jnp.asarray(self.power)
        self.bin_edges = jnp.asarray(self.bin_edges)
        self.bin_centres = jnp.asarray(self.bin_centres)

        for attr in ("bin_avg", "nsamples", "variance"):
            value = getattr(self, attr)
            if value is not None:
                setattr(self, attr, jnp.asarray(value))

        n_bins = len(self.bin_centres)
        if n_bins > 0:
            if len(self.bin_edges) != n_bins + 1:
                raise ValueError(
                    "bin_edges must have length n_bins + 1 = "
                    f"{n_bins + 1}, got {len(self.bin_edges)}."
                )
            if self.power.shape[0] != n_bins:
                raise ValueError(
                    f"power must have first dimension n_bins = {n_bins}, got {self.power.shape[0]}."
                )

        if self.bin_avg is not None and len(self.bin_avg) != n_bins:
            raise ValueError(
                f"bin_avg must have length n_bins = {n_bins}, got {len(self.bin_avg)}."
            )
        if self.nsamples is not None and len(self.nsamples) != n_bins:
            raise ValueError(
                f"nsamples must have length n_bins = {n_bins}, got {len(self.nsamples)}."
            )
        if self.variance is not None and self.variance.shape[0] != n_bins:
            raise ValueError(
                "variance must have first dimension n_bins = "
                f"{n_bins}, got {self.variance.shape[0]}."
            )


def _magnitude_grid(x: Sequence[jax.Array]) -> jax.Array:
    """Return the magnitude of a Cartesian grid defined by 1-D axes."""
    squares = [jnp.square(jnp.asarray(axis)) for axis in x]
    meshes = jnp.meshgrid(*squares, indexing="ij", sparse=True)
    total = sum(meshes[1:], meshes[0]) if meshes else jnp.asarray(0.0)
    return jnp.sqrt(total)


def _getbins(
    bins: jax.Array | np.ndarray | int,
    coord_mags: jax.Array,
    log: bool,
    bins_upto_boxlen: bool | None = None,
) -> jax.Array:
    """Return radial bin edges."""
    if np.iterable(bins) and not _is_scalar(bins):
        return jnp.asarray(bins)

    if bins_upto_boxlen is None:
        warnings.warn(
            (
                "In the future, bins will be generated by default up to the smallest "
                "length over any dimension, instead of the largest magnitude for the box."
                "Set bins_upto_boxlen to silence this warning."
            ),
            stacklevel=2,
            category=FutureWarning,
        )
        bins_upto_boxlen = False

    if bins_upto_boxlen:
        max_radius = min(
            float(jnp.min(jnp.max(coord_mags, axis=axis))) for axis in range(coord_mags.ndim)
        )
    else:
        max_radius = float(jnp.max(coord_mags))

    if not log:
        return jnp.linspace(float(jnp.min(coord_mags)), max_radius, int(bins) + 1)

    positive = coord_mags[coord_mags > 0]
    mn = float(jnp.min(positive))
    return jnp.logspace(jnp.log10(mn), jnp.log10(max_radius), int(bins) + 1)


def _normalize_boxlength_axes(boxlength: float | Sequence[float], dim: int) -> list[float]:
    """Normalize ``boxlength`` to a per-axis list of floats."""
    if _is_scalar(boxlength):
        return [float(boxlength)] * dim

    axes = [float(value) for value in boxlength]
    if len(axes) != dim:
        raise ValueError(f"boxlength must be a scalar or have length {dim}.")
    return axes


def _resolve_radial_weights(
    freq: list[jax.Array],
    kmag: jax.Array,
    k_weights: Callable[[list[jax.Array], jax.Array], jax.Array] | jax.Array | float,
    ignore_zero_mode: bool,
) -> jax.Array:
    """Return the k-space weights used during angular averaging."""
    if callable(k_weights):
        radial_weights = jnp.asarray(k_weights(freq, kmag))
    elif _is_scalar(k_weights):
        radial_weights = jnp.ones_like(kmag) * float(k_weights)
    else:
        radial_weights = jnp.asarray(k_weights)

    if radial_weights.shape != kmag.shape:
        raise ValueError(
            "k_weights must have the same shape as the averaged k-magnitude grid. "
            f"Got {radial_weights.shape} instead of {kmag.shape}."
        )

    if ignore_zero_mode:
        radial_weights = jnp.logical_and(radial_weights, ignore_zero_absk(freq, kmag))

    if radial_weights.dtype == jnp.bool_:
        radial_weights = radial_weights.astype(float)

    return radial_weights


def _resolve_bins_upto_boxlen(
    bins: int | jax.Array | np.ndarray, bins_upto_boxlen: bool | None
) -> bool:
    """Resolve the default ``bins_upto_boxlen`` behavior once."""
    if not np.iterable(bins) and bins_upto_boxlen is None:
        warnings.warn(
            (
                "In the future, bins will be generated by default up to the smallest "
                "length over any dimension, instead of the largest magnitude for the box."
                "Set bins_upto_boxlen to silence this warning."
            ),
            stacklevel=2,
            category=FutureWarning,
        )
        return False

    return bool(bins_upto_boxlen)


def _bin_centres_from_edges(bin_edges: jax.Array, log_bins: bool) -> jax.Array:
    """Return the linear or logarithmic bin centres from precomputed edges."""
    if log_bins:
        if bool(jnp.any(bin_edges <= 0)):
            raise ValueError(
                "log_bins=True requires all bin edges to be strictly positive. "
                f"Got bin_edges with minimum value {float(jnp.min(bin_edges))}."
            )
        return jnp.exp((jnp.log(bin_edges[1:]) + jnp.log(bin_edges[:-1])) / 2)

    return (bin_edges[1:] + bin_edges[:-1]) / 2


def _get_binweights(
    coord_mags: jax.Array,
    weights: jax.Array | float,
    bins: jax.Array | np.ndarray | int,
    average: bool = True,
    bin_ave: bool = True,
    log_bins: bool = False,
    bins_upto_boxlen: bool | None = None,
) -> tuple[jax.Array, jax.Array, jax.Array]:
    """Assign grid cells to radial bins and compute per-bin weights."""
    bin_edges = _getbins(bins, coord_mags, log_bins, bins_upto_boxlen=bins_upto_boxlen)
    indx = jnp.digitize(coord_mags.reshape(-1), bin_edges)

    if _is_scalar(weights):
        sumweights = jnp.bincount(indx, length=len(bin_edges) + 1)[1:-1]
        weighted_coords = coord_mags.reshape(-1) * float(weights)
    else:
        weights_arr = jnp.asarray(weights)
        if weights_arr.dtype == jnp.bool_:
            weights_arr = weights_arr.astype(float)
        if coord_mags.shape != weights_arr.shape:
            raise ValueError(
                "coords and weights must have the same shape!",
                coord_mags.shape,
                weights_arr.shape,
            )
        sumweights = jnp.bincount(indx, weights=weights_arr.reshape(-1), length=len(bin_edges) + 1)[
            1:-1
        ]
        weighted_coords = (weights_arr * coord_mags).reshape(-1)

    if average:
        binweight = sumweights
    else:
        binweight = 1 * sumweights
        sumweights = jnp.ones_like(binweight)

    bin_values = bin_edges
    if bin_ave:
        numer = jnp.bincount(indx, weights=weighted_coords, length=len(bin_edges) + 1)[1:-1]
        bin_values = jnp.where(binweight > 0, numer / binweight, jnp.nan)

    return indx, bin_values, sumweights


def _field_average(
    indx: jax.Array,
    field: jax.Array,
    weights: jax.Array | float,
    sumweights: jax.Array,
) -> jax.Array:
    """Return the weighted radial average of a field."""
    field = jnp.asarray(field)
    if not _is_scalar(weights):
        weights_arr = jnp.asarray(weights)
        if field.shape != weights_arr.shape:
            raise ValueError(
                "The field and weights must have the same shape!", field.shape, weights_arr.shape
            )
    weighted_field = field * weights

    real = jnp.bincount(
        indx, weights=jnp.real(weighted_field).reshape(-1), length=len(sumweights) + 2
    )[1:-1]
    real = jnp.where(sumweights > 0, real / sumweights, jnp.nan)

    if field.dtype.kind == "c":
        imag = jnp.bincount(
            indx, weights=jnp.imag(weighted_field).reshape(-1), length=len(sumweights) + 2
        )[1:-1]
        imag = jnp.where(sumweights > 0, imag / sumweights, jnp.nan)
        return real + 1j * imag

    return real


def _field_variance(
    indx: jax.Array,
    field: jax.Array,
    average: jax.Array,
    weights: jax.Array | float,
    v1: jax.Array,
) -> jax.Array:
    """Return the weighted variance of a radially averaged field."""
    field = jnp.asarray(field)
    if field.dtype.kind == "c":
        raise NotImplementedError("Cannot use a complex field when computing variance.")

    average_field = jnp.concatenate((jnp.zeros(1), average, jnp.zeros(1)))[indx]
    if _is_scalar(weights):
        weights_arr = float(weights)
        v2 = v1
    else:
        weights_arr = jnp.asarray(weights).reshape(-1)
        v2 = jnp.bincount(indx, weights=weights_arr**2, length=len(v1) + 2)[1:-1]

    residual = (field.reshape(-1) - average_field) ** 2 * weights_arr
    denom = v1 - v2 / v1
    cell_variance = jnp.bincount(indx, weights=residual, length=len(v1) + 2)[1:-1]
    cell_variance = jnp.where(denom > 0, cell_variance / denom, jnp.nan)
    return cell_variance * v2 / v1**2


def angular_average(
    field: jax.Array,
    coords: jax.Array | Sequence[jax.Array],
    bins: int | jax.Array | np.ndarray,
    weights: jax.Array | float = 1.0,
    average: bool = True,
    bin_ave: bool = True,
    get_variance: bool = False,
    log_bins: bool = False,
    interpolation_method: str | Callable | None = None,
    interp_points_generator: Callable[[jnp.ndarray, int], tuple[jnp.ndarray, jnp.ndarray]]
    | None = None,
    bins_upto_boxlen: bool | None = None,
) -> tuple[jax.Array, jax.Array, jax.Array | None, jax.Array]:
    """Average a field within radial bins.

    Notes
    -----
    The JAX implementation currently supports only direct binning
    (``interpolation_method=None``).
    """
    del interp_points_generator
    field = jnp.asarray(field)
    ndim = field.ndim

    if interpolation_method is not None:
        raise NotImplementedError(
            "powerbox.jax.angular_average does not yet support interpolation-based averaging."
        )

    if isinstance(coords, list | tuple):
        if len(coords) != ndim:
            raise ValueError(
                "list of coords must be same length as field.ndim. "
                f"Got {len(coords)} instead of {ndim}"
            )
        coord_mags = _magnitude_grid(coords)
    else:
        coord_mags = jnp.asarray(coords)
        if coord_mags.shape != field.shape:
            raise ValueError("coords must have the same shape as the field")

    indx, bins_out, sumweights = _get_binweights(
        coord_mags,
        weights,
        bins,
        average,
        bin_ave=bin_ave,
        log_bins=log_bins,
        bins_upto_boxlen=bins_upto_boxlen,
    )

    if bool(jnp.any(sumweights == 0)):
        warnings.warn("One or more radial bins had no cells within it.", stacklevel=2)

    average_field = _field_average(indx, field, weights, sumweights)
    variance = None
    if get_variance:
        variance = _field_variance(indx, field, average_field, weights, sumweights)

    return average_field, bins_out, variance, sumweights


def angular_average_nd(
    field: jax.Array,
    coords: Sequence[jax.Array],
    bins: int | jax.Array | np.ndarray,
    ndims_to_avg: int | None = None,
    weights: jax.Array | float = 1.0,
    interpolation_method: str | Callable | None = None,
    **kwargs,
) -> tuple[jax.Array, jax.Array, jax.Array | None, jax.Array]:
    """Average a field over a subset of its leading dimensions."""
    field = jnp.asarray(field)
    if ndims_to_avg is None:
        ndims_to_avg = field.ndim

    if not 0 < ndims_to_avg <= field.ndim:
        raise ValueError(
            f"ndims_to_avg should be between 1 and field.ndim, got {ndims_to_avg} and {field.ndim}"
        )

    if interpolation_method is not None:
        raise NotImplementedError(
            "powerbox.jax.angular_average_nd does not yet support interpolation-based averaging."
        )

    moved_field = jnp.moveaxis(
        field,
        tuple(range(ndims_to_avg)),
        tuple(range(field.ndim - ndims_to_avg, field.ndim)),
    )

    moved_weights = weights
    if not _is_scalar(weights) and jnp.asarray(weights).ndim == field.ndim:
        moved_weights = jnp.moveaxis(
            jnp.asarray(weights),
            tuple(range(ndims_to_avg)),
            tuple(range(field.ndim - ndims_to_avg, field.ndim)),
        )

    outshape = moved_field.shape[: moved_field.ndim - ndims_to_avg]
    averages: list[jax.Array] = []
    bins_list: list[jax.Array] = []
    variances: list[jax.Array] = []
    sample_weights: list[jax.Array] = []

    for idx in np.ndindex(outshape):
        index = tuple(int(i) for i in idx)
        current_weights = moved_weights
        if not _is_scalar(moved_weights) and jnp.asarray(moved_weights).ndim != ndims_to_avg:
            current_weights = jnp.asarray(moved_weights)[index]

        avg, avg_bins, variance, sumweights = angular_average(
            field=moved_field[index],
            coords=coords[:ndims_to_avg],
            bins=bins,
            weights=current_weights,
            interpolation_method=None,
            **kwargs,
        )
        averages.append(avg)
        bins_list.append(avg_bins)
        sample_weights.append(sumweights)
        if variance is not None:
            variances.append(variance)

    first_shape = averages[0].shape[0]
    out = jnp.stack(averages, axis=1).reshape((first_shape, *outshape))
    outbins = jnp.stack(bins_list, axis=1).reshape((first_shape, *outshape))
    outwght = jnp.stack(sample_weights, axis=1).reshape((first_shape, *outshape))
    outvar = None
    if variances:
        outvar = jnp.stack(variances, axis=1).reshape((first_shape, *outshape))

    return out, outbins, outvar, outwght


def power2delta(freq: list[jax.Array]) -> jax.Array:
    r"""Convert power :math:`P(k)` to dimensionless power."""
    dim = len(freq)
    coords = jnp.meshgrid(*freq, indexing="ij", sparse=True)
    absk = jnp.sqrt(sum((coord**2 for coord in coords[1:]), coords[0] ** 2))
    solid_angle = 2 * np.pi ** (dim / 2) / gamma(dim / 2)
    return solid_angle * (absk / (2 * np.pi)) ** dim


def ignore_zero_absk(freq: list[jax.Array], kmag: jax.Array | None) -> jax.Array:
    r"""Return a mask with zero weights where :math:`|k| = 0`."""
    del freq
    if kmag is None:
        raise ValueError("kmag must be provided when masking |k| = 0 modes.")
    return ~jnp.isclose(kmag, 0)


def ignore_zero_ki(freq: list[jax.Array], kmag: jax.Array | None = None) -> jax.Array:
    r"""Return a mask with zero weights where any :math:`k_i = 0`."""
    res_ndim = len(kmag.shape) if kmag is not None else len(freq)
    coords = jnp.stack(jnp.meshgrid(*freq[:res_ndim], indexing="ij", sparse=False))
    return ~jnp.any(coords == 0, axis=0)


def get_power(
    deltax: jax.Array,
    boxlength: float | Sequence[float],
    deltax2: jax.Array | None = None,
    N: int | Sequence[int] | None = None,
    a: float = 1.0,
    b: float = 1.0,
    remove_shotnoise: bool = True,
    vol_normalised_power: bool = True,
    bins: int | jax.Array | np.ndarray | None = None,
    res_ndim: int | None = None,
    weights: jax.Array | None = None,
    weights2: jax.Array | None = None,
    dimensionless: bool = True,
    get_variance: bool = False,
    log_bins: bool = False,
    ignore_zero_mode: bool = False,
    k_weights: Callable[[list[jax.Array], jax.Array], jax.Array] | jax.Array | float = 1,
    nthreads: int | None = None,
    prefactor_fnc: Callable[[list[jax.Array]], jax.Array] | None = None,
    interpolation_method: str | Callable | None = None,
    interp_points_generator: Callable[[jnp.ndarray, int], tuple[jnp.ndarray, jnp.ndarray]]
    | None = None,
    bins_upto_boxlen: bool | None = None,
) -> PowerSpectrum:
    """Calculate the isotropic power spectrum of a JAX field.

    Notes
    -----
    The JAX implementation currently supports gridded fields only. Discrete samples
    (``N is not None``) and interpolation-based averaging are intentionally deferred.
    """
    del remove_shotnoise, weights, weights2, dimensionless, nthreads

    if N is not None:
        raise NotImplementedError(
            "powerbox.jax.get_power does not yet support discrete samples. "
            "Pass a gridded field and omit `N`."
        )

    if interpolation_method is not None or interp_points_generator is not None:
        raise NotImplementedError(
            "powerbox.jax.get_power does not yet support interpolation-based averaging."
        )

    deltax = jnp.asarray(deltax)
    deltax2 = None if deltax2 is None else jnp.asarray(deltax2)
    dim = deltax.ndim

    boxlength_axes = _normalize_boxlength_axes(boxlength, dim)

    if deltax2 is not None and deltax.shape != deltax2.shape:
        raise ValueError("deltax and deltax2 must have the same shape!")

    shape = deltax.shape
    volume = float(np.prod(boxlength_axes))

    ft, freq = dft.fft(deltax, L=boxlength_axes, a=a, b=b)
    ft2 = dft.fft(deltax2, L=boxlength_axes, a=a, b=b)[0] if deltax2 is not None else ft

    power = jnp.real(ft * jnp.conj(ft2) / volume**2)
    if vol_normalised_power:
        power = power * volume
    if prefactor_fnc is not None:
        power = power * jnp.asarray(prefactor_fnc(freq))

    if res_ndim is None:
        res_ndim = dim
    if not 0 <= res_ndim <= dim:
        raise ValueError(f"res_ndim must be between 0 and {dim}, got {res_ndim}")

    if res_ndim == 0:
        return PowerSpectrum(
            power=power,
            bin_edges=jnp.array([]),
            bin_centres=jnp.array([]),
            k_unbinned=tuple(freq),
        )

    if bins is None:
        bins = int(np.prod(shape[:res_ndim]) ** (1.0 / res_ndim) / 2.2)

    kmag = _magnitude_grid([axis for i, axis in enumerate(freq) if i < res_ndim])
    radial_weights = _resolve_radial_weights(freq, kmag, k_weights, ignore_zero_mode)
    bins_upto_boxlen = _resolve_bins_upto_boxlen(bins, bins_upto_boxlen)
    bin_edges = _getbins(bins, kmag, log_bins, bins_upto_boxlen)
    bin_centres = _bin_centres_from_edges(bin_edges, log_bins)

    avg_power, bin_avg, variance, nsamples = angular_average_nd(
        field=power,
        coords=freq[:res_ndim],
        bins=bin_edges,
        ndims_to_avg=res_ndim,
        bin_ave=True,
        get_variance=get_variance,
        log_bins=log_bins,
        weights=radial_weights,
        interpolation_method=None,
        bins_upto_boxlen=bins_upto_boxlen,
    )

    if res_ndim < dim:
        if bin_avg.ndim > 1:
            bin_avg = bin_avg[(slice(None),) + (0,) * (bin_avg.ndim - 1)]
        if nsamples.ndim > 1:
            nsamples = nsamples[(slice(None),) + (0,) * (nsamples.ndim - 1)]

    return PowerSpectrum(
        power=avg_power,
        bin_edges=bin_edges,
        bin_centres=bin_centres,
        bin_avg=bin_avg,
        nsamples=nsamples,
        variance=variance,
        k_unbinned=tuple(freq[res_ndim:]) if res_ndim < dim else None,
    )
